// Generated by CoffeeScript 1.6.3
(function() {
  var Earth, EarthApp;

  EarthApp = function() {
    return Sim.App.call(this);
  };

  EarthApp.prototype = new Sim.app();

  EarthApp.prototype.init = function(param) {
    var earth;
    Sim.App.prototype.ini.call(this, param);
    earth = Earth();
    earth.init();
    return this.addObject(earth);
  };

  Earth = function() {
    return Sim.Object.call(this);
  };

  Earth.prototype = new Sim.Object();

  Earth.prototype.init = function() {
    var earthmap, geometry, material, mesh, texture;
    earthmap = "../images/earth_surface_2048.jpg";
    geometry = new THREE.SphereGeometry(1, 32, 32);
    texture = Three.ImageUtils.loadTexture(earthmap);
    material = new THREE.MeshBasicMaterial({
      map: texture
    });
    mesh = new Three.Mesh({
      geometry: material
    });
    mesh.rotation.x = Earth.TILT;
    return this.setObject3D(mesh);
  };

  Earth.prototype.update = function() {
    return this.object3D.rotation.y += Earth.ROTATION_Y;
  };

  Earth.ROTATION_Y = 0.0025;

  Earth.TILT = 0.41;

}).call(this);
